init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

test_script:
  - sh: |
      # test MySQL
      sudo systemctl start mysql
      mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e 'USE mysql; SELECT Host,User FROM `user`;'
      sudo systemctl disable mysql
      dpkg -l 'mysql-*'|grep '^ii'
      
build: off
