init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 
install:
  - sh: |
      # remove existing version of MySQL
      sudo apt-get remove -y mysql-server && sudo apt-get -y autoremove

  - sh: |
      # configure_apt before installing MySQL
      MYSQL_ROOT_PASSWORD="Password12!"
      echo "mysql-server mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}" | sudo debconf-set-selections &&
      echo "mysql-server mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}" | sudo debconf-set-selections

  - sh: |
      # Install MySQL
      MYSQL_VERSION=5.7.26
      OS_RELEASE=$(source "/etc/os-release" && echo $VERSION_ID)
      OS_ARCH=$(dpkg --print-architecture)
      sudo apt-get install -y -qq libmecab2 libaio1 
      REPO_URL=http://repo.mysql.com/apt/ubuntu/pool/mysql-5.7/m/mysql-community
      TMP_DIR=$(mktemp -d)
      pushd -- "${TMP_DIR}"
      for pkg in mysql-common mysql-community-client mysql-client mysql-community-server mysql-server; do
          curl -fsSL -O "$REPO_URL/${pkg}_${MYSQL_VERSION}-1ubuntu${OS_RELEASE}_${OS_ARCH}.deb"
          sudo dpkg -i "${pkg}_${MYSQL_VERSION}-1ubuntu${OS_RELEASE}_${OS_ARCH}.deb"
      done
      popd

test_script:
  - sh: |
      # test MySQL
      sudo systemctl start mysql
      mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e 'USE mysql; SELECT Host,User FROM `user`;'
      sudo systemctl disable mysql
      dpkg -l 'mysql-*'|grep '^ii'
      
build: off
